# Generated by Django 3.1.6 on 2021-08-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210816_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ('id', 'last_name', 'first_name', 'email', 'password', 'company', 'created_at', 'updated_at')},
        ),
    ]
