# Generated by Django 3.1.6 on 2021-08-16 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='None', max_length=80, null=True)),
                ('time_worked', models.CharField(max_length=255, null=True)),
                ('in_comment', models.TextField(default='None', null=True)),
                ('out_comment', models.TextField(default='None', null=True)),
                ('date_in', models.DateField(null=True)),
                ('date_out', models.DateField(null=True)),
                ('clocked_in_at', models.TimeField()),
                ('clocked_out_at', models.TimeField(null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockSystem', to='employees.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockinlocation', to='company.location')),
            ],
            options={
                'ordering': ('id', 'is_flagged', 'employee', 'date_in', 'date_out', 'clocked_in_at', 'clocked_out_at', 'time_worked', 'role', 'location', 'in_comment', 'out_comment', 'created_at', 'updated_at'),
            },
        ),
    ]
