# Generated by Django 3.1.6 on 2021-08-29 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210817_2226'),
        ('company', '0007_auto_20210824_1615'),
        ('reports', '0002_auto_20210816_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocksystem',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockin_employee', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='clocksystem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockin_location', to='company.location'),
        ),
    ]
