# Generated by Django 3.1.6 on 2021-09-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210829_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clocksystem',
            options={'ordering': ('created_at', 'updated_at', 'id', 'is_flagged', 'employee', 'date_in', 'date_out', 'clocked_in_at', 'clocked_out_at', 'time_worked', 'role', 'location', 'in_comment', 'out_comment')},
        ),
    ]
