# Generated by Django 3.1.6 on 2021-09-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210905_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clocksystem',
            options={'ordering': ('id', 'is_flagged', 'employee', 'date_in', 'date_out', 'clocked_in_at', 'clocked_out_at', 'time_worked', 'role', 'location', 'in_comment', 'out_comment', 'created_at', 'updated_at')},
        ),
    ]
