# Generated by Django 3.1.6 on 2021-09-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20210929_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocksystem',
            name='flag_message',
            field=models.TextField(null=True),
        ),
    ]
