# Generated by Django 3.1.6 on 2021-10-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20210930_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clocksystem',
            options={'ordering': ('id', 'is_flagged', 'flag_message', 'employee', 'date_in', 'date_out', 'clocked_in_at', 'clocked_out_at', 'time_worked', 'role', 'location_in', 'in_comment', 'out_comment', 'created_at', 'updated_at')},
        ),
        migrations.RenameField(
            model_name='clocksystem',
            old_name='location',
            new_name='location_in',
        ),
    ]
