# Generated by Django 3.1.6 on 2021-10-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_auto_20210930_1804'),
        ('reports', '0009_auto_20211010_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clocksystem',
            options={'ordering': ('id', 'is_flagged', 'flag_message', 'employee', 'date_in', 'date_out', 'clocked_in_at', 'clocked_out_at', 'time_worked', 'role', 'location_in', 'location_out', 'in_comment', 'out_comment', 'created_at', 'updated_at')},
        ),
        migrations.AddField(
            model_name='clocksystem',
            name='location_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clockout_location', to='company.location'),
        ),
    ]
