# Generated by Django 3.1.6 on 2021-08-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('id', 'name', 'image', 'created_at', 'updated_at')},
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(null=True, upload_to='static/media/img/company-logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
