# Generated by Django 3.1.6 on 2021-08-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210817_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
