# Generated by Django 3.1.6 on 2021-08-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210817_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
