# Generated by Django 3.1.6 on 2021-08-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(null=True, upload_to='media/logos/'),
        ),
    ]
