# Generated by Django 3.1.6 on 2021-09-29 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20210928_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#26225B', max_length=100, null=True)),
                ('font_color', models.CharField(default='color', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='company.company')),
            ],
            options={
                'ordering': ('id', 'company', 'color', 'font_color', 'created_at', 'updated_at'),
            },
        ),
    ]
