# Generated by Django 3.1.6 on 2021-09-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20210929_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysetting',
            name='font_color',
            field=models.CharField(default='#F8F8F8', max_length=100, null=True),
        ),
    ]
