# Generated by Django 3.1.6 on 2021-09-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20210929_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysetting',
            options={'ordering': ('id', 'company', 'color', 'font_color', 'background_color', 'created_at', 'updated_at')},
        ),
        migrations.AddField(
            model_name='companysetting',
            name='background_color',
            field=models.CharField(default='#F8F8F8', max_length=50, null=True),
        ),
    ]
