# Generated by Django 3.1.6 on 2021-09-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20210929_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysetting',
            options={'ordering': ('id', 'company', 'color', 'font_color', 'background_color', 'time_zone', 'contact_name', 'contact_number', 'created_at', 'updated_at')},
        ),
        migrations.AddField(
            model_name='companysetting',
            name='contact_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='contact_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
