# Generated by Django 3.1.6 on 2021-09-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20210929_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysetting',
            name='contact_number',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
