# Generated by Django 3.1.6 on 2021-09-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20210929_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(null=True, upload_to='media/company-image'),
        ),
    ]
